services:
  api:
    build:
      context: .
      dockerfile: groceries-api/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_KEY=${API_KEY}
      - DI_ENDPOINT=${DI_ENDPOINT}
      - DI_KEY=${DI_KEY}
    volumes:
      - ${DB_PATH:-./db}:/app/db
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:3000/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s